stages:
  - unit-tests
image: ubuntu

unit-tests:
  stage: unit-tests
  script:
    - echo "Installing dependencies"
    - apt-get update
    - apt-get install -y cmake make gcc g++ gfortran python3 python3-numpy python3-yaml libblas-dev liblapack-dev
    - base_dir=$PWD
    - echo "Checking code style"
    - python3 ./tools/coding_standard/homepage.py .
    - python3 ./tools/coding_standard/whitespace.py .
    - python3 ./tools/coding_standard/permissions.py .
    - echo "Building lammps in directory $base_dir"
    - mkdir build && cd build
    - cmake ../cmake
    - cmake -D ENABLE_TESTING=on .
    - cmake -DCMAKE_BUILD_TYPE=Debug .
    - cmake -D PKG_MOLECULE=yes .
    - cmake -D PKG_KSPACE=yes .
    - cmake -D PKG_RIGID=yes .
    - cmake -D PKG_MISC=yes .
    - cmake -D PKG_ELECTRODE=yes .
    - cmake --build . 
    - cmake -D PKG_INTEL=yes .
    - cmake --build .
    # need to run unit tests w/o root privileges
    - adduser tester
    - chown -R tester $base_dir
    - runuser -u tester ctest
    - echo "running tests in examples/PACKAGES/electrode subdirectory of $base_dir"
    - lmpbin=$base_dir/build/lmp
    - cd $base_dir/examples/PACKAGES/electrode/check_amat/
    - bash check.sh $lmpbin
    - cd $base_dir/examples/PACKAGES/electrode/check_etypes/
    - bash check.sh $lmpbin
    - cd $base_dir/examples/PACKAGES/electrode/check_ffield/
    - bash check.sh $lmpbin
    - cd $base_dir/examples/PACKAGES/electrode/check_intel/
    - bash check.sh $lmpbin
