image: ubuntu:latest

test:

  before_script:

    # Install Linux Packages:
    - apt-get update
    - hostname
    - export HOME=/builds/exaalt/
    - env
    - apt-get --yes --force-yes install gfortran libblas-dev liblapack-dev
    - apt-get --yes --force-yes install cmake python gcc cmake-data g++ git wget
    - apt-get --yes --force-yes install pkg-config python-numpy python3-numpy libopenmpi-dev

    # Build LATTE:
    - cd /builds/exaalt/
    - git clone https://github.com/lanl/LATTE.git
    - cd LATTE
    - cp ./makefiles/makefile.CHOICES.gfort.lapack.lmp makefile.CHOICES
    - make

    # Build LAMMPS:
    - cd /builds/exaalt/lammps/lib/latte/
    - cp Makefile.lammps.gfortran Makefile.lammps
    - cd /builds/exaalt/lammps/src/
    - make yes-latte
    - make yes-molecule
    - make serial

  script:

    # Test LAMMPS-LATTE Example:
    - cd /builds/exaalt/lammps/examples/latte/
    - ../../src/lmp_serial -in in.latte.water

