extraction:
  cpp:
    configure:
      command:
      - "mkdir build"
      - "cd build"
      - "cmake -G Ninja -C ../cmake/presets/minimal.cmake ../cmake"
    index:
      build_command:
      - "cd build"
      - "ninja"
  python:
    python_setup:
      version: 3
