name: documentation
on:
  push:
    branches:
      - master
    paths:
      - 'doc/*'

jobs:
  build:
    continue-on-error: true
    runs-on: ubuntu-latest
    container: "lammps/buildenv:fedora32_mingw"
    strategy:
      matrix:
        target: ['html', 'pdf', 'spelling']
    steps:
      - uses: actions/checkout@master
      - name: Generate ${{ matrix.target }}
        run: make -C doc ${{ matrix.target }}
