name: style
on:
  push:
    branches:
      - master

jobs:
  check_whitespace:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pyyaml
          sudo apt install -y ninja-build
      - uses: actions/checkout@master
      - name: Configure
        run: cmake -B build -G Ninja -D Python3_EXECUTABLE=$(which python) -S cmake
      - name: Check for whitespace errors
        run: cmake --build build --target check-whitespace

  check_permissions:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pyyaml
          sudo apt install -y ninja-build
      - uses: actions/checkout@master
      - name: Configure
        run: cmake -B build -G Ninja -D Python3_EXECUTABLE=$(which python) -S cmake
      - name: Check file permissions
        run: cmake --build build --target check-permissions
